### ISSUE TITLE
Remove dependency on plyr package

### ISSUE THREAD

**Issue by hazimtimimi** [hazimtimimi/global_report#1]
With the introduction of dplyr, there are clashes (eg identical function names) with older code relying on plyr. Would be good to weed out all such dependencies and remove plyr from the codebase.

**Comment by tomhiatt** [comment]
Okay after an inital look, plyr can be easily removed for the most part. The estimates figures still use it, but these can be reworked along with the challenge of one year of forecast data.

**Comment by hazimtimimi** [comment]
Okey dokey. Could I leave this with you please?

**Comment by tomhiatt** [comment]
Bien sur !
