### ISSUE TITLE
What are lines 67 - 69 in load_data_from_database.r all about?

### ISSUE THREAD

**Issue by hazimtimimi** [hazimtimimi/global_report#2]
There is this bobby dazzler:

d <- merge(n[n$year>=min(d$year), 1:19], d[d$all_areas_covered==1 |
  is.na(d$all_areas_covered),], all.x=T)

Need to investigate and clear up!

**Comment by tomhiatt** [comment]
Okay, I just got off a time call with my 2008 self and as he explained it to me, this bit of hairy code is trying to format `view_TME_master_dr_surveillance` to play nicer with the other data.frames by:
- Removing records that aren't explicitly covering a whole country
- Adding in past years so the number of records is identical with `view_TME_master_notification` (with `NA`s filled in for missing data.)
- Adding in grouping variables and other meta (1:19 in notifications)

Without direct access to the database I can't fully test these things. And perhaps you might want to just add grouping variables and years into the original view. Or you may want to bust out your fancy SQLery into the `sqlFetch` command to filter out all the sub-coverage records. 

But if you just want to leave things in their _functional_ state, then I'm happy to write a more descriptive comment.

**Comment by hazimtimimi** [comment]
That's fine, thanks for the time travel. Please just add the bullet points you mentioned as comments above lines 67 - 69 in `load_data_from_database.r` and close this issue!

Thanks :-)

**Comment by tomhiatt** [comment]
Done!
