### ISSUE TITLE
XLConnect library crashing my R installation?

### ISSUE THREAD

**Issue by hazimtimimi** [hazimtimimi/global_report#3]
Tom, R / RStudio bombs out now when I run `create_tables_figures.r`. Is there any reason why you introduced the XLConnect package instead of using good ol' RODBC to read in data from Excel?

**Comment by hazimtimimi** [comment]
OK, scrap that. Turned out it was dplyr inner_join() was the culrpit, and updating Rcpp did the trick. See https://github.com/hadley/dplyr/issues/1066.

**Comment by tomhiatt** [comment]
I haven't tried rodbc on excel files, but I know they can be fickle. My goal was to connect to the files raw with no need for pre-formatting of the files (export to cvs, etc.) XLConnect has been the most reliable for me so far.
