### ISSUE TITLE
Map 2.21 looks wrong

### ISSUE THREAD

**Issue by hazimtimimi** [hazimtimimi/global_report#5]
I think the map of 2.21 is wrong. For one thing, quite a few countries in western Europe, plus Canada have not reported notifications to us yet, but they appear as if they have in the map.

Looking at the code you are using that weird n.t dataframe instead of the actual notifications dataframe n  (line 218 of Maps.r)

Also, are you distinguishing between countries that can provide the full age disaggregation for all categories from those such as Thailand that simply give < 15 and 15+ categories? What point is this map trying to make?

**Comment by tomhiatt** [comment]
Thank you for your message. We value your feedback and will consider it for the improvement of our products. Thanks for choosing Global TB Report for all your global TB  surveillance needs.
